apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: teleport-ingress-cm
  annotations: 
    kubernetes.io/ingress.class: nginx
    cert-manager.io/issuer: "duckdns-letsencrypt-staging"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - grantvoss.duckdns.org
    secretName: teleport-app-duckdns-tls
  rules:
  - host: grantvoss.duckdns.org
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: nginx-service-cm
            port:
              number: 80
