apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: teleport-ingress-cm
  annotations: 
    cert-manager.io/issuer: "letsencrypt-staging"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - teleport-app.grantvoss.duckdns.org
    secretName: quickstart-example-tls
  rules:
  - host: teleport-app.grantvoss.duckdns.org
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: nginx-service-cm
            port:
              number: 80
