apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-index-cm
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
      <title>Welcome to Teleport App Page!</title>
    </head>
    <body>
      <h1>Hello World!</h1>
      <p>Certs configured by Cert Manager</p>
    </body>
    </html>
